version: '2.2'
services:
  mc-1:
    container_name: mc-1
    hostname: manticore-1
    platform: "linux/${CPUTYPE:-arm64}"
    restart: always
    image: manticoresearch/manticore:15.1.0
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - manticore
    ports:
      - "9306:9306" # MySQL protocol
      - "9308:9308" # HTTP protocol
      - "9312:9312"
  mc-2:
    container_name: mc-2
    hostname: manticore-2
    platform: "linux/${CPUTYPE:-arm64}"
    restart: always
    image: manticoresearch/manticore:15.1.0
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - manticore
    ports:
      - "9316:9306" # MySQL protocol
      - "9318:9308" # HTTP protocol
      - "9322:9312"
  mc-3:
    container_name: mc-3
    hostname: manticore-3
    platform: "linux/${CPUTYPE:-arm64}"
    restart: always
    image: manticoresearch/manticore:15.1.0
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - manticore
    ports:
      - "9326:9306" # MySQL protocol
      - "9328:9308" # HTTP protocol
      - "9332:9312"
networks:
  manticore:
    driver: bridge